name: Latexmk

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: torumano/texlive:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build pdf
      run: latexmk bare_conf.tex

    - uses: actions/upload-artifact@v2
      with:
        name: bare_conf.pdf
        path: bare_conf.pdf
